import Head from 'next/head'
import Link from 'next/link'

import AppBar from '../src/components/AppBar'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar />
      <div className="landing">
        <div className="landing-left">
Left
        </div>
        <div className="landing-right">
Right
        </div>
      </div>
      <div className="landing1">
        <div className="landing1-left">
          Left  
        </div>
        <div className="landing1-right">
          Right
        </div>
      </div>
    </div>
  )
}
